#!/bin/bash
#1 obtain the number of input parameters, if none then quit
user=grasure
hosts=(192.168.58.129 192.168.58.130 192.168.58.134 192.168.58.135)
pcount=$#
cmd=$1 
if (($pcount != 1))
then 
	echo usage:./autoSync commands
	exit;
fi

#5 concurrent
for host in ${hosts[@]}
do
	#echo ---------autoSync $user@$host start------------
	ssh $user@${host} $cmd
	echo ---------send command to $user@$host ------------
done

